search_query_parameter: a
search_recursive_parameter: r
search_add_operator: +
search_remove_operator: '-'
facet_truncate: '32'
case_insensitive_solr_field_prefix: tm_lowercase_
lucene_on_off: 1
show_lucene_option: 0
lucene_label: Keyword
copyfield_on_off: 0
copyfiled_label: null
copyfiled_name: null
