csl_map:
  field_model:
    - type
  field_description:
    - abstract
  field_genre:
    - genre
  field_place_published_country:
    - publisher-place
  title:
    - title
  field_language:
    - language
  field_edtf_date_created:
    - original-date
  field_linked_agent:
    - author
reference_type_field: field_genre
typed_relation_map:
  'relators:cre': author
reference_type_field_map:
  'Paged Content': book
  Image: figure
