rest_oai_pmh:
  entity_type: node
view_displays:
  'oai_pmh_default_set:entity_reference_1': 'oai_pmh_default_set:entity_reference_1'
support_sets: 1
metadata_map_plugins:
  -
    label: oai_raw
    value: default_metadata_map
  -
    label: oai_dc
    value: dublin_core_rdf
  -
    label: mods
    value: mods
mods_view:
  view_machine_name: oai_pmh_data
  view_display_name: page_1
repository_name: 'Papers of Doris McCathy'
repository_email: dsu@utsc.utoronto.ca
expiration: '3600'
cache_technique: liberal_cache
